GET http://localhost:3001/
###
GET http://localhost:3001/api/persons/1
###
DELETE http://localhost:3001/api/persons/41
###

POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "mmmmkkk",
    "number": "4544"
    }